services:
  - type: web
    name: fotoropa-pro
    env: static
    staticPublishPath: .
    buildCommand: ""
    routes:
      - type: rewrite
        source: /*
        destination: /FotoRopaPro.html
